apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patches:
- path: deployment.yaml
- path: service.yaml

namespace: instavote

replicas:
  - name: vote
    count: 4

images:
  - name: schoolofdevops/vote
    newTag: v4

commonLabels:
  project: instavote
  enivronment: staging 

commonAnnotations:
  supported-by: schoolofdevops

configMapGenerator:
- name: vote-config
  envs: 
    - options.env
